import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copy } from 'esbuild-plugin-copy';
import { config } from 'dotenv';

config({ path: '.env.local' });
config({ path: '.env' });

const { OUT_DIR } = process.env;



const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: [
    './src/main.ts', 
    './styles.css'
  ],
  entryNames: '[name]',
  outbase: 'src',
  bundle: true,
  external: [
    'obsidian', 
    'electron', 		
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    ...builtins],
  loader: { '.json': 'file' },
  format: 'cjs',
  watch: !prod,
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  // sourcemap: 'both',
  // sourceRoot: './src',
  minify: prod,
  treeShaking: true,
  plugins: [
    copy({
      assets: [
        {
          from: ['./manifest.json'],
          to: './',
        },{
          from: ['./lua/utf8_filenames.lua', './lua/polyfill.lua','./lua/url.lua', './lua/markdown.lua', './lua/markdown+hugo.lua'],
          to: ['./lua/.'],
        }
      ]
    })
  ],
  outdir: OUT_DIR ?? 'dist',
}).catch(() => process.exit(1));