name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        pandoc-version: [3.1.11.1, 3.8.2.1, 3.8.3]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc-version }}/pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
          sudo dpkg -i pandoc-${{ matrix.pandoc-version }}-1-amd64.deb
      - name: Install Dependencies
        run: pnpm install
      - name: Test
        run: npm test
